### PR TITLE
python3 fixes

### PR DESCRIPTION
**Pull request by krasi-georgiev**
Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

### CODE REVIEW

**Comment by kekiefer** [comment]
Looks fine, thanks for the updates! Just one comment/question in-line for my understanding.

**Comment by krasi-georgiev** [comment]
I don't see the comment?

**Comment by kekiefer** [comment]
The change to `SPIDEV_MESSAGE_LIMIT` here: https://github.com/groupgets/pylepton/pull/66/files/2b99821c16059aab68d49451b538e430fbfbabf6#diff-cd294a51811e671f3ed3f8d662b4441f1a96a5466358a0f0c525224e6ab3b51eR47

**Comment by krasi-georgiev** [comment]
Without this I was getting `OSError: [Errno 90] Message too long` and non of the suggested fixes I found for increasing the limit worked

**Comment by krasi-georgiev** [comment]
more details here

https://github.com/groupgets/pylepton/issues/52

**Comment by kekiefer** [comment]
OK, IIRC this larger message size used to be required to work with Lepton 3 (at least when this was initially put together for rpi 3).

The comment suggests increasing `/sys/module/spidev/parameters/bufsiz` to get around this limit, did this not work, or was it just simpler to have small SPI messages?

If this works with Lepton 3.5 on rpi 4, I guess I'm OK with it as it's just one less thing to have to set up.

**Comment by krasi-georgiev** [comment]
I am running this on Rpi3 with lepton 3.5

**Comment by kekiefer** [comment]
Alright then, even better. In that case thanks again for the updates!

**Review by kekiefer — APPROVED** [review]

**Comment by krasi-georgiev** [comment]
26-Jan-21:35:31 59

**Pull request merged**
